import React, { useEffect, useRef, useState } from 'react';
import {
  Box,
  Text,
  Flex,
  Heading,
  UnorderedList,
  ListItem,
  Code,
  VStack,
  Divider,
  Portal,
  useDisclosure,
  useOutsideClick,
  useColorModeValue,
} from '@chakra-ui/react';
import { InfoIcon } from '@chakra-ui/icons';

// Define the metrics documentation object
const metricsDocumentation = {
  total_pnl: {
    name: 'Returns (Percentage)',
    description: 'The net percentage return generated by the bot over its entire trading history.',
    formula: '(Sum(Exit Price - Entry Price) × Position Size - Commissions) / Initial Capital × 100',
    dataSource: 'Calculated from closed trades in the database.',
    valueRange: {
      normalRange: 'Any value (positive or negative)',
      interpretation: {
        lowValue: 'Negative values indicate overall losses',
        highValue: 'Positive values indicate overall profits',
        optimalZone: 'Consistently positive and growing over time',
      }
    },
    commonIssues: [
      {
        description: 'Percentage return calculation might not include commission or slippage costs',
        troubleshooting: 'Ensure trade execution records accurately capture all costs',
      },
      {
        description: 'Does not account for risk taken to achieve the returns',
        troubleshooting: 'Analyze alongside risk metrics like Max Drawdown',
      }
    ],
    bestPractices: [
      'Track returns over time to identify trends in profitability',
      'Compare against other bots to understand relative performance',
    ]
  },
  win_rate: {
    name: 'Win Rate',
    description: 'The percentage of trades that resulted in a profit.',
    formula: '(Number of Winning Trades / Total Number of Closed Trades) × 100',
    dataSource: 'Calculated from trade history in the database.',
    valueRange: {
      normalRange: '0% - 100%',
      interpretation: {
        lowValue: 'Below 50% indicates more losing trades than winning trades',
        highValue: 'Above 50% indicates more winning trades than losing trades',
        optimalZone: 'Typically above 60%, but depends on strategy risk/reward profile',
      }
    },
    commonIssues: [
      {
        description: 'A small sample size of trades might not be statistically significant',
        troubleshooting: 'Wait for sufficient trades (50+) before drawing strong conclusions',
      },
      {
        description: 'High win rate doesn\'t guarantee profitability if losses exceed wins',
        troubleshooting: 'Evaluate with Average Return per Trade and Risk/Reward Ratio',
      }
    ],
    bestPractices: [
      'Monitor how win rate changes across different market conditions',
      'Use win rate as one component in evaluating strategy consistency',
    ]
  },
  average_pnl_per_trade: {
    name: 'Average Return per Trade',
    description: 'The average percentage return generated per trade, including both winning and losing trades.',
    formula: '(Sum of Trade Returns / Number of Trades) × 100',
    dataSource: 'Calculated from all closed trades in the database.',
    valueRange: {
      normalRange: 'Any value, with positive values indicating profitable strategy',
      interpretation: {
        lowValue: 'Negative values indicate the average trade is losing money',
        highValue: 'Positive values indicate the average trade is profitable',
        optimalZone: 'Any positive value, with higher being better',
      }
    },
    commonIssues: [
      {
        description: 'Can be skewed by outlier trades with large gains or losses',
        troubleshooting: 'Examine the distribution of trade returns to identify outliers',
      },
      {
        description: 'Does not account for trade frequency or capital efficiency',
        troubleshooting: 'Analyze alongside volume metrics and capital efficiency',
      }
    ],
    bestPractices: [
      'Use as a quick measure of strategy efficiency',
      'Monitor changes over time to detect strategy degradation',
      'Compare across bots to identify strongest performers',
    ]
  },
  profit_factor: {
    name: 'Profit Factor',
    description: 'Measures the ratio of gross profits to gross losses. Indicates how many dollars are won for every dollar lost.',
    formula: 'Sum of Profits from Winning Trades / |Sum of Losses from Losing Trades|',
    dataSource: 'Calculated from P&L of winning and losing trades.',
    valueRange: {
      normalRange: 'Greater than 0, with values > 1 indicating profitability',
      interpretation: {
        lowValue: 'Values below 1 indicate the bot loses more money than it makes',
        highValue: 'Values above 1.5 or 2.0 suggest a robustly profitable strategy',
        optimalZone: 'Above 1.5 is good, above 2.0 is excellent',
      }
    },
    commonIssues: [
      {
        description: 'Can be skewed by a single large winning or losing trade',
        troubleshooting: 'Analyze the distribution of trade P&L and ensure sufficient sample size',
      },
      {
        description: 'Undefined if there are no losing trades',
        troubleshooting: 'Handle division by zero in calculations; interpret as highly profitable',
      }
    ],
    bestPractices: [
      'Use as a primary indicator of overall strategy profitability efficiency',
      'Combine with Win Rate to understand if profitability comes from frequent small wins or infrequent large wins',
    ]
  },
  max_drawdown: {
    name: 'Maximum Drawdown',
    description: 'The largest peak-to-trough decline in the bot\'s equity curve, representing the maximum observed loss from a peak.',
    formula: 'Max(Peak Equity - Trough Equity) / Peak Equity',
    dataSource: 'Calculated by tracking the equity curve from trade results.',
    valueRange: {
      normalRange: '0% to 100% (lower is better)',
      interpretation: {
        lowValue: 'Indicates smaller equity declines and lower volatility/risk',
        highValue: 'Indicates significant equity declines were experienced',
        optimalZone: 'As low as possible while allowing the strategy to capture sufficient upside',
      }
    },
    commonIssues: [
      {
        description: 'Historical Max Drawdown does not guarantee future drawdowns won\'t be larger',
        troubleshooting: 'Use stress testing and consider worst-case scenarios beyond historical data',
      },
      {
        description: 'Calculation depends on the frequency of equity curve sampling',
        troubleshooting: 'Ensure consistent and sufficiently frequent calculation',
      }
    ],
    bestPractices: [
      'Use Max Drawdown as a key indicator of downside risk',
      'Compare to average returns (Calmar Ratio = Annual Return / Max Drawdown)',
      'Set risk limits based on acceptable Max Drawdown levels',
    ]
  },
  average_win_amount: {
    name: 'Average Win Amount',
    description: 'The average profit per winning trade.',
    formula: 'Sum of Profits from Winning Trades / Number of Winning Trades',
    dataSource: 'Calculated from winning trades in the database.',
    valueRange: {
      normalRange: 'Greater than 0 (higher is generally better)',
      interpretation: {
        lowValue: 'Small average wins may indicate limited profit potential',
        highValue: 'Large average wins suggest effective profit targets',
        optimalZone: 'Depends on strategy, should be higher than average loss amount',
      }
    },
    commonIssues: [
      {
        description: 'Can be skewed by outlier winning trades',
        troubleshooting: 'Examine the distribution of winning trade amounts',
      }
    ],
    bestPractices: [
      'Compare with Average Loss Amount to assess risk/reward ratio',
      'Track over time to identify changes in strategy effectiveness',
    ]
  },
  average_loss_amount: {
    name: 'Average Loss Amount',
    description: 'The average loss per losing trade.',
    formula: 'Sum of Losses from Losing Trades / Number of Losing Trades',
    dataSource: 'Calculated from losing trades in the database.',
    valueRange: {
      normalRange: 'Less than 0 (closer to zero is better)',
      interpretation: {
        lowValue: 'Smaller average losses indicate good risk management',
        highValue: 'Large average losses suggest potential issues with stop losses',
        optimalZone: 'Should be smaller in magnitude than average win amount',
      }
    },
    commonIssues: [
      {
        description: 'Can be skewed by outlier losing trades',
        troubleshooting: 'Examine the distribution of losing trade amounts',
      }
    ],
    bestPractices: [
      'Compare with Average Win Amount to ensure positive expectancy',
      'Set and review stop loss strategies to control average loss',
    ]
  },
  risk_reward_ratio: {
    name: 'Risk-Reward Ratio',
    description: 'The ratio of the average profit on winning trades to the average loss on losing trades.',
    formula: 'Average Win Amount / |Average Loss Amount|',
    dataSource: 'Calculated from average win and loss amounts.',
    valueRange: {
      normalRange: 'Greater than 0, with higher values better',
      interpretation: {
        lowValue: 'Values below 1 indicate average losses exceed average wins',
        highValue: 'Values above 2 indicate good profit potential relative to risk',
        optimalZone: 'Above 1.5, with higher values better',
      }
    },
    commonIssues: [
      {
        description: 'Does not account for win rate in overall profitability',
        troubleshooting: 'Consider alongside win rate and average return per trade',
      }
    ],
    bestPractices: [
      'Target minimum 1:1.5 or 1:2 risk-reward for most strategies',
      'Balance with realistic win rate expectations',
    ]
  },
  rank_score: {
    name: 'Rank Score',
    description: 'A composite scoring metric that combines multiple performance indicators to rank bots.',
    formula: 'Weighted combination of win rate, profit factor, returns, drawdown, and more',
    dataSource: 'Calculated from multiple performance metrics with applied weights.',
    valueRange: {
      normalRange: '0 to 100 (higher is better)',
      interpretation: {
        lowValue: 'Low scores indicate poor overall performance',
        highValue: 'High scores indicate strong overall performance',
        optimalZone: 'Top quartile relative to other bots',
      }
    },
    commonIssues: [
      {
        description: 'Complex calculation may obscure individual metric issues',
        troubleshooting: 'Examine individual components alongside the overall score',
      },
      {
        description: 'Weighting may favor certain types of performance over others',
        troubleshooting: 'Review the weighting scheme to ensure alignment with objectives',
      }
    ],
    bestPractices: [
      'Use for comparative analysis between bots',
      'Review the component metrics to understand strengths and weaknesses',
    ]
  }
};

// Add any missing metrics with a generic placeholder
export const getMetricDocumentation = (metricKey: string) => {
  return metricsDocumentation[metricKey as keyof typeof metricsDocumentation] || {
    name: metricKey.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' '),
    description: 'Metric information not yet documented.',
    formula: 'Formula not defined',
    dataSource: 'Data source not specified',
    valueRange: {
      normalRange: 'Range not specified',
      interpretation: {
        lowValue: 'Interpretation not available',
        highValue: 'Interpretation not available',
        optimalZone: 'Optimal zone not defined',
      }
    },
    commonIssues: [
      {
        description: 'Documentation pending',
        troubleshooting: 'Please check back later for complete information',
      }
    ],
    bestPractices: [
      'Documentation in progress',
    ]
  };
};

type MetricInfoTooltipProps = {
  metricKey: string;
  children: React.ReactNode;
};

const MetricInfoTooltip: React.FC<MetricInfoTooltipProps> = ({ metricKey, children }) => {
  const metric = getMetricDocumentation(metricKey);
  const { isOpen, onOpen, onClose } = useDisclosure();
  const triggerRef = useRef<HTMLDivElement>(null);
  const tooltipRef = useRef<HTMLDivElement>(null);
  const [position, setPosition] = useState({ top: 0, left: 0 });
  
  // Background colors
  const bg = useColorModeValue('white', 'gray.700');
  const borderColor = useColorModeValue('gray.200', 'gray.600');
  
  // Handle positioning of tooltip
  useEffect(() => {
    if (isOpen && triggerRef.current && tooltipRef.current) {
      const triggerRect = triggerRef.current.getBoundingClientRect();
      const tooltipRect = tooltipRef.current.getBoundingClientRect();
      const viewportHeight = window.innerHeight;
      const viewportWidth = window.innerWidth;
      
      // Initial position (centered above trigger)
      let top = triggerRect.top - tooltipRect.height - 10;
      let left = triggerRect.left + triggerRect.width/2 - tooltipRect.width/2;
      
      // Check if tooltip would go off the top of the screen
      if (top < 10) {
        // Position below trigger instead
        top = triggerRect.bottom + 10;
      }
      
      // Check if tooltip would go off the bottom of the screen
      if (top + tooltipRect.height > viewportHeight - 10) {
        // Position to the right side of the trigger
        top = triggerRect.top + triggerRect.height/2 - tooltipRect.height/2;
        left = triggerRect.right + 10;
        
        // If that would go off right edge, try left side
        if (left + tooltipRect.width > viewportWidth - 10) {
          left = triggerRect.left - tooltipRect.width - 10;
          
          // If that would go off left edge, center it as best as possible
          if (left < 10) {
            left = Math.max(10, (viewportWidth - tooltipRect.width) / 2);
            top = Math.max(10, viewportHeight/2 - tooltipRect.height/2);
          }
        }
      }
      
      // Check if tooltip would go off the left side of the screen
      if (left < 10) {
        left = 10;
      }
      
      // Check if tooltip would go off the right side of the screen
      if (left + tooltipRect.width > viewportWidth - 10) {
        left = viewportWidth - tooltipRect.width - 10;
      }
      
      setPosition({ top, left });
    }
  }, [isOpen]);
  
  // Close tooltip when clicking outside
  useOutsideClick({
    ref: tooltipRef,
    handler: () => {
      if (isOpen) onClose();
    },
  });
  
  // Handle keyboard events for better accessibility
  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      isOpen ? onClose() : onOpen();
    } else if (e.key === 'Escape' && isOpen) {
      onClose();
    }
  };

  return (
    <>
      <Flex 
        ref={triggerRef}
        alignItems="center" 
        tabIndex={0}
        role="button"
        aria-label={`Show information about ${metric.name}`}
        aria-expanded={isOpen}
        onKeyDown={handleKeyDown}
        cursor="pointer"
        onClick={isOpen ? onClose : onOpen}
        _hover={{ textDecoration: 'underline' }}
        _focus={{ 
          boxShadow: 'outline', 
          outline: 'none',
          borderRadius: 'sm',
          px: 1
        }}
      >
        {children}
        <InfoIcon 
          ml={1} 
          color="blue.400" 
          w={3} 
          h={3} 
          aria-hidden="true" 
        />
      </Flex>
      
      {isOpen && (
        <Portal>
          <Box
            ref={tooltipRef}
            position="fixed"
            top={`${position.top}px`}
            left={`${position.left}px`}
            zIndex={9999}
            maxW="sm"
            overflow="auto"
            maxH="80vh"
            bg={bg}
            boxShadow="xl"
            borderRadius="md"
            borderWidth="1px"
            borderColor={borderColor}
            p={4}
            role="tooltip"
            aria-label={`Information about ${metric.name}`}
          >
            <VStack align="start" spacing={2}>
              <Heading size="sm">{metric.name}</Heading>
              <Text>{metric.description}</Text>
              
              <Divider />
              
              <Text fontWeight="bold">Formula:</Text>
              <Code p={1}>{metric.formula}</Code>
              
              <Text fontWeight="bold">Data Source:</Text>
              <Text fontSize="sm">{metric.dataSource}</Text>
              
              <Text fontWeight="bold">Normal Range:</Text>
              <Text fontSize="sm">{metric.valueRange.normalRange}</Text>
              
              <Text fontWeight="bold">Interpretation:</Text>
              <UnorderedList pl={4} fontSize="sm">
                <ListItem>Low Values: {metric.valueRange.interpretation.lowValue}</ListItem>
                <ListItem>High Values: {metric.valueRange.interpretation.highValue}</ListItem>
                <ListItem>Optimal: {metric.valueRange.interpretation.optimalZone}</ListItem>
              </UnorderedList>
              
              <Text fontWeight="bold">Common Issues:</Text>
              <UnorderedList pl={4} fontSize="sm">
                {metric.commonIssues.map((issue, idx) => (
                  <ListItem key={idx}>
                    {issue.description} - {issue.troubleshooting}
                  </ListItem>
                ))}
              </UnorderedList>
              
              <Text fontWeight="bold">Best Practices:</Text>
              <UnorderedList pl={4} fontSize="sm">
                {metric.bestPractices.map((practice, idx) => (
                  <ListItem key={idx}>{practice}</ListItem>
                ))}
              </UnorderedList>
            </VStack>
          </Box>
        </Portal>
      )}
    </>
  );
};

export default MetricInfoTooltip; 