import React from 'react';
import {
  Tooltip,
  Box,
  Text,
  Flex,
  Heading,
  UnorderedList,
  ListItem,
  Code,
  VStack,
  Divider,
} from '@chakra-ui/react';
import { InfoIcon } from '@chakra-ui/icons';

// Define the metrics documentation object
const metricsDocumentation = {
  total_pnl: {
    name: 'Total P&L (Profit and Loss)',
    description: 'The net profit or loss generated by the bot over its entire trading history.',
    formula: 'Sum(Exit Price - Entry Price) × Position Size - Commissions',
    dataSource: 'Calculated from closed trades in the database.',
    valueRange: {
      normalRange: 'Any value (positive or negative)',
      interpretation: {
        lowValue: 'Negative values indicate overall losses',
        highValue: 'Positive values indicate overall profits',
        optimalZone: 'Consistently positive and growing over time',
      }
    },
    commonIssues: [
      {
        description: 'P&L calculation might not include commission or slippage costs',
        troubleshooting: 'Ensure trade execution records accurately capture all costs',
      },
      {
        description: 'Does not account for risk taken to achieve the P&L',
        troubleshooting: 'Analyze alongside risk metrics like Max Drawdown and Sharpe Ratio',
      }
    ],
    bestPractices: [
      'Track P&L over time to identify trends in profitability',
      'Compare against initial capital to understand returns relative to investment',
    ]
  },
  win_rate: {
    name: 'Win Rate',
    description: 'The percentage of trades that resulted in a profit.',
    formula: '(Number of Winning Trades / Total Number of Closed Trades) × 100',
    dataSource: 'Calculated from trade history in the database.',
    valueRange: {
      normalRange: '0% - 100%',
      interpretation: {
        lowValue: 'Below 50% indicates more losing trades than winning trades',
        highValue: 'Above 50% indicates more winning trades than losing trades',
        optimalZone: 'Typically above 60%, but depends on strategy risk/reward profile',
      }
    },
    commonIssues: [
      {
        description: 'A small sample size of trades might not be statistically significant',
        troubleshooting: 'Wait for sufficient trades (50+) before drawing strong conclusions',
      },
      {
        description: 'High win rate doesn\'t guarantee profitability if losses exceed wins',
        troubleshooting: 'Evaluate with Profit Factor, Average Profit per Trade, and Risk/Reward Ratio',
      }
    ],
    bestPractices: [
      'Monitor how win rate changes across different market conditions',
      'Use win rate as one component in evaluating strategy consistency',
    ]
  },
  profit_factor: {
    name: 'Profit Factor',
    description: 'Measures the ratio of gross profits to gross losses. Indicates how many dollars are won for every dollar lost.',
    formula: 'Sum of Profits from Winning Trades / |Sum of Losses from Losing Trades|',
    dataSource: 'Calculated from P&L of winning and losing trades.',
    valueRange: {
      normalRange: 'Greater than 0, with values > 1 indicating profitability',
      interpretation: {
        lowValue: 'Values below 1 indicate the bot loses more money than it makes',
        highValue: 'Values above 1.5 or 2.0 suggest a robustly profitable strategy',
        optimalZone: 'Above 1.5 is good, above 2.0 is excellent',
      }
    },
    commonIssues: [
      {
        description: 'Can be skewed by a single large winning or losing trade',
        troubleshooting: 'Analyze the distribution of trade P&L and ensure sufficient sample size',
      },
      {
        description: 'Undefined if there are no losing trades',
        troubleshooting: 'Handle division by zero in calculations; interpret as highly profitable',
      }
    ],
    bestPractices: [
      'Use as a primary indicator of overall strategy profitability efficiency',
      'Combine with Win Rate to understand if profitability comes from frequent small wins or infrequent large wins',
    ]
  },
  max_drawdown: {
    name: 'Maximum Drawdown',
    description: 'The largest peak-to-trough decline in the bot\'s equity curve, representing the maximum observed loss from a peak.',
    formula: 'Max(Peak Equity - Trough Equity) / Peak Equity',
    dataSource: 'Calculated by tracking the equity curve from trade results.',
    valueRange: {
      normalRange: '0% to 100% (lower is better)',
      interpretation: {
        lowValue: 'Indicates smaller equity declines and lower volatility/risk',
        highValue: 'Indicates significant equity declines were experienced',
        optimalZone: 'As low as possible while allowing the strategy to capture sufficient upside',
      }
    },
    commonIssues: [
      {
        description: 'Historical Max Drawdown does not guarantee future drawdowns won\'t be larger',
        troubleshooting: 'Use stress testing and consider worst-case scenarios beyond historical data',
      },
      {
        description: 'Calculation depends on the frequency of equity curve sampling',
        troubleshooting: 'Ensure consistent and sufficiently frequent calculation',
      }
    ],
    bestPractices: [
      'Use Max Drawdown as a key indicator of downside risk',
      'Compare to average returns (Calmar Ratio = Annual Return / Max Drawdown)',
      'Set risk limits based on acceptable Max Drawdown levels',
    ]
  },
  sharpe_ratio: {
    name: 'Sharpe Ratio',
    description: 'Measures risk-adjusted return by comparing excess return over a risk-free rate to volatility.',
    formula: '(Portfolio Return - Risk-Free Rate) / Standard Deviation of Excess Return',
    dataSource: 'Calculated from time series of returns and a benchmark risk-free rate.',
    valueRange: {
      normalRange: 'Can be negative or positive (higher is better)',
      interpretation: {
        lowValue: 'Negative values indicate returns worse than the risk-free rate',
        highValue: 'Values above 1 are good, above 2 excellent, above 3 exceptional',
        optimalZone: 'Consistently above 1.0-1.5',
      }
    },
    commonIssues: [
      {
        description: 'Sensitive to calculation period and chosen risk-free rate',
        troubleshooting: 'Ensure consistency when comparing different bots or periods',
      },
      {
        description: 'Assumes returns are normally distributed',
        troubleshooting: 'Supplement with metrics like Sortino Ratio or Max Drawdown',
      }
    ],
    bestPractices: [
      'Use to compare risk-adjusted performance across different strategies',
      'Annualize for easier comparison across timeframes',
    ]
  },
  average_win_amount: {
    name: 'Average Win Amount',
    description: 'The average profit per winning trade.',
    formula: 'Sum of Profits from Winning Trades / Number of Winning Trades',
    dataSource: 'Calculated from winning trades in the database.',
    valueRange: {
      normalRange: 'Greater than 0 (higher is generally better)',
      interpretation: {
        lowValue: 'Small average wins may indicate limited profit potential',
        highValue: 'Large average wins suggest effective profit targets',
        optimalZone: 'Depends on strategy, should be higher than average loss amount',
      }
    },
    commonIssues: [
      {
        description: 'Can be skewed by outlier winning trades',
        troubleshooting: 'Examine the distribution of winning trade amounts',
      }
    ],
    bestPractices: [
      'Compare with Average Loss Amount to assess risk/reward ratio',
      'Track over time to identify changes in strategy effectiveness',
    ]
  },
  average_loss_amount: {
    name: 'Average Loss Amount',
    description: 'The average loss per losing trade.',
    formula: 'Sum of Losses from Losing Trades / Number of Losing Trades',
    dataSource: 'Calculated from losing trades in the database.',
    valueRange: {
      normalRange: 'Less than 0 (closer to zero is better)',
      interpretation: {
        lowValue: 'Smaller average losses indicate good risk management',
        highValue: 'Large average losses suggest potential issues with stop losses',
        optimalZone: 'Should be smaller in magnitude than average win amount',
      }
    },
    commonIssues: [
      {
        description: 'Can be skewed by outlier losing trades',
        troubleshooting: 'Examine the distribution of losing trade amounts',
      }
    ],
    bestPractices: [
      'Compare with Average Win Amount to ensure positive expectancy',
      'Set and review stop loss strategies to control average loss',
    ]
  },
  expectancy: {
    name: 'Expectancy',
    description: 'The average amount a trader can expect to win or lose per trade over time.',
    formula: '(Win Rate × Average Win) - ((1 - Win Rate) × Average Loss)',
    dataSource: 'Derived from win rate and average trade P&L values.',
    valueRange: {
      normalRange: 'Any value, with positive values indicating profitable system',
      interpretation: {
        lowValue: 'Negative values indicate an unprofitable system',
        highValue: 'Higher positive values indicate more profit per trade',
        optimalZone: 'Any positive value, with higher being better',
      }
    },
    commonIssues: [
      {
        description: 'Does not account for trade frequency or capital requirements',
        troubleshooting: 'Analyze alongside volume metrics and capital efficiency',
      }
    ],
    bestPractices: [
      'Use as a quick measure of strategy efficiency',
      'Monitor changes over time to detect strategy degradation',
    ]
  },
  risk_reward_ratio: {
    name: 'Risk-Reward Ratio',
    description: 'The ratio of the average profit on winning trades to the average loss on losing trades.',
    formula: 'Average Win Amount / |Average Loss Amount|',
    dataSource: 'Calculated from average win and loss amounts.',
    valueRange: {
      normalRange: 'Greater than 0, with higher values better',
      interpretation: {
        lowValue: 'Values below 1 indicate average losses exceed average wins',
        highValue: 'Values above 2 indicate good profit potential relative to risk',
        optimalZone: 'Above 1.5, with higher values better',
      }
    },
    commonIssues: [
      {
        description: 'Does not account for win rate in overall profitability',
        troubleshooting: 'Consider alongside win rate and expectancy',
      }
    ],
    bestPractices: [
      'Target minimum 1:1.5 or 1:2 risk-reward for most strategies',
      'Balance with realistic win rate expectations',
    ]
  },
  rank_score: {
    name: 'Rank Score',
    description: 'A composite scoring metric that combines multiple performance indicators to rank bots.',
    formula: 'Weighted combination of win rate, profit factor, expectancy, drawdown, and more',
    dataSource: 'Calculated from multiple performance metrics with applied weights.',
    valueRange: {
      normalRange: '0 to 100 (higher is better)',
      interpretation: {
        lowValue: 'Low scores indicate poor overall performance',
        highValue: 'High scores indicate strong overall performance',
        optimalZone: 'Top quartile relative to other bots',
      }
    },
    commonIssues: [
      {
        description: 'Complex calculation may obscure individual metric issues',
        troubleshooting: 'Examine individual components alongside the overall score',
      },
      {
        description: 'Weighting may favor certain types of performance over others',
        troubleshooting: 'Review the weighting scheme to ensure alignment with objectives',
      }
    ],
    bestPractices: [
      'Use for comparative analysis between bots',
      'Review the component metrics to understand strengths and weaknesses',
    ]
  }
};

// Add any missing metrics with a generic placeholder
export const getMetricDocumentation = (metricKey: string) => {
  return metricsDocumentation[metricKey as keyof typeof metricsDocumentation] || {
    name: metricKey.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' '),
    description: 'Metric information not yet documented.',
    formula: 'Formula not defined',
    dataSource: 'Data source not specified',
    valueRange: {
      normalRange: 'Range not specified',
      interpretation: {
        lowValue: 'Interpretation not available',
        highValue: 'Interpretation not available',
        optimalZone: 'Optimal zone not defined',
      }
    },
    commonIssues: [
      {
        description: 'Documentation pending',
        troubleshooting: 'Please check back later for complete information',
      }
    ],
    bestPractices: [
      'Documentation in progress',
    ]
  };
};

type MetricInfoTooltipProps = {
  metricKey: string;
  children: React.ReactNode;
};

const MetricInfoTooltip: React.FC<MetricInfoTooltipProps> = ({ metricKey, children }) => {
  const metric = getMetricDocumentation(metricKey);
  const [isTooltipOpen, setIsTooltipOpen] = React.useState(false);
  
  // Handle keyboard events for better accessibility
  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      setIsTooltipOpen(!isTooltipOpen);
    } else if (e.key === 'Escape' && isTooltipOpen) {
      setIsTooltipOpen(false);
    }
  };

  return (
    <Tooltip
      label={
        <Box p={2} maxW="sm">
          <VStack align="start" spacing={2}>
            <Heading size="sm">{metric.name}</Heading>
            <Text>{metric.description}</Text>
            
            <Divider />
            
            <Text fontWeight="bold">Formula:</Text>
            <Code p={1}>{metric.formula}</Code>
            
            <Text fontWeight="bold">Data Source:</Text>
            <Text fontSize="sm">{metric.dataSource}</Text>
            
            <Text fontWeight="bold">Normal Range:</Text>
            <Text fontSize="sm">{metric.valueRange.normalRange}</Text>
            
            <Text fontWeight="bold">Interpretation:</Text>
            <UnorderedList pl={4} fontSize="sm">
              <ListItem>Low Values: {metric.valueRange.interpretation.lowValue}</ListItem>
              <ListItem>High Values: {metric.valueRange.interpretation.highValue}</ListItem>
              <ListItem>Optimal: {metric.valueRange.interpretation.optimalZone}</ListItem>
            </UnorderedList>
            
            <Text fontWeight="bold">Common Issues:</Text>
            <UnorderedList pl={4} fontSize="sm">
              {metric.commonIssues.map((issue, idx) => (
                <ListItem key={idx}>
                  {issue.description} - {issue.troubleshooting}
                </ListItem>
              ))}
            </UnorderedList>
            
            <Text fontWeight="bold">Best Practices:</Text>
            <UnorderedList pl={4} fontSize="sm">
              {metric.bestPractices.map((practice, idx) => (
                <ListItem key={idx}>{practice}</ListItem>
              ))}
            </UnorderedList>
          </VStack>
        </Box>
      }
      placement="top"
      hasArrow
      bg="gray.700"
      color="white"
      gutter={10}
      openDelay={300}
      closeDelay={100}
      isOpen={isTooltipOpen}
      onOpen={() => setIsTooltipOpen(true)}
      onClose={() => setIsTooltipOpen(false)}
      aria-label={`Information about ${metric.name}`}
    >
      <Flex 
        alignItems="center" 
        tabIndex={0}
        role="button"
        aria-label={`Show information about ${metric.name}`}
        aria-expanded={isTooltipOpen}
        onKeyDown={handleKeyDown}
        cursor="pointer"
        _hover={{ textDecoration: 'underline' }}
        _focus={{ 
          boxShadow: 'outline', 
          outline: 'none',
          borderRadius: 'sm',
          px: 1
        }}
      >
        {children}
        <InfoIcon 
          ml={1} 
          color="blue.400" 
          w={3} 
          h={3} 
          aria-hidden="true" 
        />
      </Flex>
    </Tooltip>
  );
};

export default MetricInfoTooltip; 